gcc 5-7: fix build error for x86 targets
building any of i?86, x86_64, and x32 targets on a *musl* host
with a recent gcc host version (in my testing gcc 11), causes
the following build error:

../../src_gcc/gcc/config/i386/i386.c:8750:18: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
  8750 |   bool error_p = NULL;
       |                  ^~~~

the issue affects the 3 supported gcc versions 5.3.0, 6.5.0 and 7.5.0.